# Generated by Django 4.0.3 on 2025-03-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('RG', 'Regression'), ('CL', 'Classification')], max_length=2)),
                ('algorithm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('data_set', models.FileField(upload_to='datasets/')),
            ],
        ),
        migrations.CreateModel(
            name='ModelDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.JSONField()),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.model')),
            ],
        ),
    ]
